apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-client
  labels:
    app: admin-client
spec:
  replicas: 3
  template:
    metadata:
      name: admin-client
      labels:
        app: admin-client
    spec:
      containers:
        - name: admin-client
          image: aurelius0523/admin-client-docker
          imagePullPolicy: IfNotPresent
          env:
            - name: server_port
              value: "7080"
            - name: admin_url
              value: "http://admin-server-service:8080"
            - name: prefer_ip
              value: "true"
          ports:
            - containerPort: 7080
      restartPolicy: Always
  selector:
    matchLabels:
      app: admin-client

---
apiVersion: v1
kind: Service
metadata:
  name: admin-client-service
spec:
  selector:
    app: admin-client
  ports:
    - port: 7080
  type: LoadBalancer