kind: Deployment
apiVersion: apps/v1

metadata:
  name: admin-server-deployment
  labels:
    app: admin-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: aurelius0523/admin-server-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1

metadata:
  name: admin-server-lb

spec:
  type: LoadBalancer
  selector:
    app: admin-server
  ports:
    - targetPort: 8080
      port: 8080
